from langgraph.graph import MessagesState
import operator
from typing import Annotated, Any

class main_state(MessagesState):
    
    query: Annotated[str, "The query to be answered."]
    paras: Annotated[list[str], "The paragraphs to be used for answering the query."]
    suggested_answer: Annotated[str, "The answer generated by the generator node."]
    answer: Annotated[str, "The answer to the query."]
    